---
openapi: 3.0.0
info:
  title: Showtime API
  description: This is the API of the Showtime service
  contact:
    email: helene.coullon@imt-atlantique.fr
  license:
    name: GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.0
servers:
- url: http://localhost:3202
  description: For local tests
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
paths:
  /:
    get:
      tags:
      - developers
      summary: home page of the service
      description: |
        Nothing to do
      operationId: home
      responses:
        "200":
          description: welcome message
          content:
            text/html:
              schema:
                type: string
                example: <h1>Test</h1>
  /showtimes:
    get:
      tags:
      - developers
      summary: get the full JSON database
      description: |
        Nothing to do
      operationId: get_schedule
      responses:
        "200":
          description: full JSON
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllSchedule'
  /showmovies/{date}:
    get:
      tags:
      - developers
      summary: get the schedule by date
      description: |
        Get the schedule for a given date
      operationId: get_movies_bydate
      parameters:
      - name: date
        in: path
        description: date.
        required: true
        style: simple
        explode: false
        schema:
          maximum: 1
          minimum: 1
          type: string
      responses:
        "200":
          description: Schedule
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schedule'
        "400":
          description: bad input parameter
components:
  schemas:
    AllSchedule:
      required:
      - schedule
      type: object
      properties:
        schedule:
          type: array
          items:
            $ref: '#/components/schemas/Schedule'
    Schedule:
      required:
      - date
      - movies
      type: object
      properties:
        date:
          type: string
          example: "20151130"
        movies:
          type: array
          items:
            type: string
            example: tt0108052
